services:
  web:
    container_name: effective_team
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
          condition: service_healthy
    ports:
      - 8000:8000
  db:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    env_file:
      - project.env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
volumes:
  pgdata:
    driver: local

    