# Generated by Django 5.0.4 on 2024-04-23 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='name',
            new_name='creator_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='member_name',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='member',
            new_name='member_name',
        ),
    ]
