# Generated by Django 5.0.4 on 2024-05-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0002_alter_team_team_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['stamina']},
        ),
    ]
