# Generated by Django 5.0.4 on 2024-04-23 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0002_rename_name_creator_creator_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_creator',
            new_name='creator_name',
        ),
    ]
