# Generated by Django 5.0.4 on 2024-05-04 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0003_alter_member_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
    ]
