# Generated by Django 5.0.4 on 2024-04-23 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0003_rename_team_creator_team_creator_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='member_name',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='creator_name',
            new_name='creator',
        ),
    ]
