# Generated by Django 5.0.4 on 2024-04-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0005_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_id',
            field=models.IntegerField(default=0),
        ),
    ]
