# Generated by Django 5.0.4 on 2024-04-25 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0007_alter_transaction_sender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='team_app.creator'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='team_app.creator'),
        ),
    ]
