# Generated by Django 5.0.4 on 2024-04-25 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0008_alter_transaction_receiver_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
