# Generated by Django 5.0.4 on 2024-04-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0010_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_size',
            field=models.IntegerField(default=1),
        ),
    ]
